bot-token: TOKEN

main-server-id: 953775916771835914
owner-id: 490537526436560896
log-channel: 1064893422340690021

file-name: "%Y-%m-%d-%H-%M-%S"

schedule:
  hour: 3 # The hour to run the backup, in 24 hour time
  minute: 0 # The minute to run the backup

  days_of_week: # The days of the week to run a backup | 0 = Monday, 6 = Sunday, etc
    - 0

backups:
  - 
    directory: /var/www/html
    zip-identifier: WEB
  - 
    directory: /root/data
    zip-identifier: DATA