bot-token: MTA2NDg5MzEzMjEzMjU5Nzg2MA.GfcPH_.GPiY5ov4StdW0AhQIYLb7ASipXVjsMS47Tmp44

main-server-id: 953775916771835914
owner-id: 490537526436560896
log-channel: 1064893422340690021

file-name: "%Y-%m-%d-%H-%M-%S"

backups:
  - 
    directory: /var/www/html
    zip-identifier: WEB
  - 
    directory: /root/data
    zip-identifier: DATA